### ISSUE TITLE
MAC打包报错

### ISSUE THREAD

**Issue by t880216t** [yaoleia/antd-pro-simple#1]
楼主，我执行`yarn build`报错额
···
```shell 
$ NODE_ENV=production webpack --config ./build/webpack.main.prod.config.js
Hash: 65172dea9612c86d3624
Version: webpack 4.44.2
Time: 8710ms
Built at: 2020-11-25 5:35:33 ├F10: PM┤
      Asset     Size  Chunks                   Chunk Names
    main.js  186 KiB       0  [emitted]        main
main.js.map  938 KiB       0  [emitted] [dev]  main
Entrypoint main = main.js main.js.map
  [2] external "path" 42 bytes {0} [built]
  [6] external "fs" 42 bytes {0} [built]
  [9] external "electron" 42 bytes {0} [built]
 [14] external "util" 42 bytes {0} [built]
 [34] external "assert" 42 bytes {0} [built]
 [44] external "events" 42 bytes {0} [built]
 [49] external "stream" 42 bytes {0} [built]
 [74] ./main/main.js 1.23 KiB {0} [built]
[112] external "buffer" 42 bytes {0} [built]
[144] external "https" 42 bytes {0} [built]
    + 135 hidden modules
  • electron-builder  version=22.8.1 os=19.4.0
  • loaded configuration  file=package.json ("build" field)
  • loaded parent configuration  file=/Users/xxx/workspace/xxxx/xxxxx/node_modules/_electron-webpack@2.8.2@electron-webpack/out/electron-builder.js
  • writing effective config  file=release/0.0.1/builder-effective-config.yaml
  ⨯ open /Users/mictest/workspace/fight/mobileManager/node_modules/umi/node_modules/@umijs/preset-built-in/node_modules/@umijs/bundler-webpack/node_modules/webpack/node_modules/@webassemblyjs/wasm-parser/node_modules/@webassemblyjs/ast/node_modules/@webassemblyjs/wast-parser/node_modules/@webassemblyjs/helper-code-frame/node_modules/@webassemblyjs/wast-printer/node_modules/@webassemblyjs/ast/node_modules/@webassemblyjs/helper-module-context/node_modules/@webassemblyjs/ast/node_modules/@webassemblyjs/helper-module-context/node_modules/@webassemblyjs/ast/node_modules/@webassemblyjs/helper-module-context/node_modules/@webassemblyjs/ast/node_modules/@webassemblyjs/wast-parser/node_modules/@webassemblyjs/ast/node_modules/@webassemblyjs/helper-module-context/node_modules/@webassemblyjs/ast/node_modules/@webassemblyjs/helper-module-context/node_modules/@webassemblyjs/ast/node_modules/@webassemblyjs/helper-module-context/node_modules/@webassemblyjs/ast/node_modules/@webassemblyjs/helper-module-context/node_modules/@webassemblyjs/ast/package.json: file name too long
github.com/develar/app-builder/pkg/node-modules.(*Collector).resolveDependency
	/Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:192
github.com/develar/app-builder/pkg/node-modules.(*Collector).processDependencies
	/Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:95
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
	/Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:56
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
	/Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
	/Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
	/Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
	/Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
	/Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
	/Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
	/Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
	/Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
	/Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
	/Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
	/Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
	/Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
	/Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
	/Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
	/Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
	/Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
	/Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
	/Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
	/Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
	/Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
	/Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
	/Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
	/Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
	/Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
	/Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.ConfigureCommand.func1
	/Volumes/data/Documents/app-builder/pkg/node-modules/tree.go:41
github.com/alecthomas/kingpin.(*actionMixin).applyActions
	/Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/actions.go:28
github.com/alecthomas/kingpin.(*Application).applyActions
	/Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:557
github.com/alecthomas/kingpin.(*Application).execute
	/Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:390  
  ⨯ /Users/mictest/workspace/fight/mobileManager/node_modules/_app-builder-bin@3.5.10@app-builder-bin/mac/app-builder exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE  stackTrace=
                                                                                                                                                                              Error: /Users/mictest/workspace/fight/mobileManager/node_modules/_app-builder-bin@3.5.10@app-builder-bin/mac/app-builder exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
                                                                                                                                                                                  at ChildProcess.<anonymous> (/Users/mictest/workspace/fight/mobileManager/node_modules/_builder-util@22.8.1@builder-util/src/util.ts:243:14)
                                                                                                                                                                                  at Object.onceWrapper (events.js:422:26)
                                                                                                                                                                                  at ChildProcess.emit (events.js:315:20)
                                                                                                                                                                                  at maybeClose (internal/child_process.js:1021:16)
                                                                                                                                                                                  at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
error Command failed with exit code 1.
```

**Comment by t880216t** [comment]
解决了npm 版本的问题，还yarn可以了
